### ISSUE TITLE
The type or namespace name -'FluentAssertions'  missing error help

### ISSUE THREAD

**Issue by Asw-S93** [JohnnyTurbo/BloonsTD#1]
The type or namespace name 'FluentAssertions' could not be found (are you missing a using directive or an assembly reference?)

**Comment by JohnnyTurbo** [comment]
Hello there, "FluentAssertions" is a library I use for writing Unit tests in this project. You should be able to just delete the "tests" directory without breaking anything if you don't need to see how I setup unit testing. If you do want unit testing, they you can just download FluentAssertions and add the library to the Project/Packages folder. Hope that helps you get this project running!
